### ISSUE TITLE
Talk with actual test user(s)

### ISSUE THREAD

**Issue by samolds** [samolds/principia#10]
We should get in contact with someone who would actually be interested in using our thing and get feedback.

I'm thinking possibly physics professors at The U or maybe a high school teacher if someone has those sorts of connections. I think the easiest type of test user to get would be students currently taking Physics classes, but we should try and talk to a professor first.

Here's a list of all of the [faculty in the Physics department](http://www.physics.utah.edu/index.php/people).

**Comment by samolds** [comment]
Matthew and I were talking and we think the Physics Tutors would probably have awesome feedback.

**Comment by MatthewTurnerCS** [comment]
Scheduled some meetings, more to come.
