### ISSUE TITLE
Support Deleting Entire Sim

### ISSUE THREAD

**Issue by MatthewTurnerCS** [samolds/principia#134]
Allow a user to delete their saved simulation entirely.

**Comment by samolds** [comment]
Delete simulations via the "My Simulations" page or just the actual simulation's page.
Perform an ajax `.delete` request to the `editXSimulation` handlers. Add some logic bits in the `editGenericHandler` to check if `r.Method == DELETE` or whatever. If `DELETE`, delete thing from datastore, respond with yay or error. If on the simulation's page, redirect the user to "My Simulations" if success. If on the "My Simulations" page, Toast a success or failure.
