### ISSUE TITLE
Become familiar with Javascript Best Practices

### ISSUE THREAD

**Issue by daltonwallace** [samolds/principia#18]
@dannylp @samolds @MatthewTurnerCS 

Resources:

JS Best Practices:
http://addyosmani.com/resources/essentialjsdesignpatterns/book/

PhysicsJS:
https://github.com/wellcaffeinated/PhysicsJS/wiki/Fundamentals
http://wellcaffeinated.net/PhysicsJS/basic-usage

Create a toy PhysicsJS application using his tutorials and javascript best practices

**Comment by samolds** [comment]
This will likely be an ongoing process, but I think we've got a good idea of the direction we're heading.
