### ISSUE TITLE
Origin body doesn't properly scale when zooming in or out

### ISSUE THREAD

**Issue by samolds** [samolds/principia#205]

**Comment by MatthewTurnerCS** [comment]
I think this was intended behavior. So long as the origin is always positioned at the right coordinates, I thought we all had agreed at some point for the image to stay a constant size.

**Comment by samolds** [comment]
Sorry, that was an unclear title. It specifically is the positioning of it:
<img width="500" alt="normal" src="https://cloud.githubusercontent.com/assets/1863557/14577406/d00497dc-0330-11e6-9a8f-4db9671ab9fe.png">

<img width="500" alt="zoomin" src="https://cloud.githubusercontent.com/assets/1863557/14577409/d759324a-0330-11e6-9e15-313e54ec0b96.png">

<img width="500" alt="zoomout" src="https://cloud.githubusercontent.com/assets/1863557/14577410/da0a0aaa-0330-11e6-8b09-761ba5a0ae11.png">
