### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by MatthewTurnerCS** [samolds/principia#27]
Persist both simulations and comments, possibly using GorillaMux for routing.

**Comment by samolds** [comment]
Note to self: Look through datastore stuff to help Dalton

**Comment by samolds** [comment]
Currently not persisting actual simulator data.

For the prototype we're going to create separate javascript modules with hardcoded initialized states and not worry about exporting simulator state to the database or initializing a simulator from a json blob from the database.
