### ISSUE TITLE
Make keyframe editablity more clear

### ISSUE THREAD

**Issue by samolds** [samolds/principia#58]
Right now it seems kind of "broken" when the user can't drag on a new body to simulator when not in a key frame because there is no feedback. Also, it would be cool to highlight which keyframe is currently being edited.

**Comment by MatthewTurnerCS** [comment]
Keyframes are highlighted now. Not sure what the best feedback would be for failing to add an element... maybe we could change the "solution box" to be a more general purpose "output box" post-prototype.
